# Generated by Django 5.0.14 on 2025-09-30 22:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "duracion",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="duración en años",
                    ),
                ),
                (
                    "cupo_maximo",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="cupo máximo de alumnos"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
            ],
            options={
                "verbose_name": "carrera",
                "verbose_name_plural": "carreras",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "dni",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000000),
                            django.core.validators.MaxValueValidator(99999999),
                        ],
                        verbose_name="DNI",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="nombre")),
                ("apellido", models.CharField(max_length=50, verbose_name="apellido")),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de nacimiento"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="teléfono"
                    ),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="dirección")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("ALUMNO", "Alumno"),
                            ("DOCENTE", "Docente"),
                            ("PRECEPTOR", "Preceptor"),
                        ],
                        default="ALUMNO",
                        max_length=10,
                        verbose_name="rol",
                    ),
                ),
                (
                    "debe_cambiar_password",
                    models.BooleanField(
                        default=True, verbose_name="debe cambiar contraseña"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InscripcionCarrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inscripcion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de inscripción"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "alumno",
                    models.ForeignKey(
                        limit_choices_to={"rol": "ALUMNO"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carreras_inscripciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="alumno",
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones_carrera",
                        to="core.carrera",
                        verbose_name="carrera",
                    ),
                ),
            ],
            options={
                "verbose_name": "inscripción a carrera",
                "verbose_name_plural": "inscripciones a carreras",
                "unique_together": {("alumno", "carrera")},
            },
        ),
        migrations.AddField(
            model_name="usuario",
            name="carreras_inscripto",
            field=models.ManyToManyField(
                related_name="alumnos",
                through="core.InscripcionCarrera",
                to="core.carrera",
                verbose_name="carreras inscripto",
            ),
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "cupo_maximo",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="cupo máximo de alumnos"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materias",
                        to="core.carrera",
                        verbose_name="carrera",
                    ),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"rol": "DOCENTE"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materias_dictadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="docente",
                    ),
                ),
            ],
            options={
                "verbose_name": "materia",
                "verbose_name_plural": "materias",
                "ordering": ["carrera", "nombre"],
                "unique_together": {("nombre", "carrera")},
            },
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inscripcion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de inscripción"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "alumno",
                    models.ForeignKey(
                        limit_choices_to={"rol": "ALUMNO"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="alumno",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones",
                        to="core.materia",
                        verbose_name="materia",
                    ),
                ),
            ],
            options={
                "verbose_name": "inscripción",
                "verbose_name_plural": "inscripciones",
                "unique_together": {("alumno", "materia")},
            },
        ),
    ]
