# Generated by Django 5.2.5 on 2025-10-28 23:59

from django.db import migrations

def create_default_groups(apps, schema_editor):
    # This function is intentionally left empty as we don't want to create any default groups
    # Groups should be created manually through the admin interface
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_default_groups, reverse_code=migrations.RunPython.noop),
    ]
