# Generated by Django 5.2.5 on 2025-11-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['nombre'], 'verbose_name': 'materia', 'verbose_name_plural': 'materias'},
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='materia',
            name='carreras',
            field=models.ManyToManyField(related_name='materias', to='core.carrera', verbose_name='carreras'),
        ),
        migrations.AddField(
            model_name='materia',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único de la materia', max_length=20, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='cupo_maximo',
            field=models.PositiveSmallIntegerField(default=30, help_text='Número máximo de alumnos que pueden inscribirse a esta materia', verbose_name='cupo máximo de alumnos'),
        ),
        migrations.AddConstraint(
            model_name='materia',
            constraint=models.UniqueConstraint(fields=('nombre', 'codigo'), name='unique_nombre_codigo'),
        ),
        migrations.RemoveField(
            model_name='materia',
            name='carrera',
        ),
    ]
