# Generated by Django 5.2.5 on 2025-11-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_migrate_carrera_to_carreras'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='materia',
            name='unique_nombre_codigo',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(help_text='Nombre único de la materia', max_length=100, unique=True, verbose_name='nombre'),
        ),
    ]
